# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
podspec_name = "AlfrescoCore.podspec"

platform :ios do
  desc "Release new version with a patch version bump"
  lane :patch do
  	release("patch")
  end

  desc "Release a new version with a minor version bump"
  lane :minor do
  	release("minor")
  end

  desc "Release a new version with a major bump"
  lane :major do
  	release("major")
  end

  def release(type)
  	version_bump_podspec(path: podspec_name,
  						 bump_type: type)
  end

end

