# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pr:
  - master
  - release-*
  - develop

pool:
  vmImage: 'macos-latest'

steps:
# ---------------------------------------
# Run core module tests
# ---------------------------------------
- task: Xcode@5
  displayName: 'Running tests'
  inputs:
    actions: 'test'
    scheme: 'AlfrescoCore'
    sdk: 'iphonesimulator'
    configuration: 'Debug'
    xcWorkspacePath: 'AlfrescoCore/AlfrescoCore.xcodeproj'
    useXcpretty: true
    publishJUnitResults: 'build/reports/junit.xml'

# ---------------------------------------
# Publish test results
# ---------------------------------------
- task: PublishTestResults@2
  displayName: 'Publish test'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'build/reports/junit.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Publishing test results'

# ---------------------------------------
# Build core module
# ---------------------------------------
- task: Xcode@5
  displayName: 'Building Alfresco iOS DBP SDK - core module'
  inputs:
    actions: 'clean build analyze archive'
    scheme: 'AlfrescoCore'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: 'AlfrescoCore/AlfrescoCore.xcodeproj'
    xcodeVersion: 'default'
    args: '-archivePath $(agent.buildDirectory)/ios-dbp-sdk-core'

# ---------------------------------------
# Package core module
# ---------------------------------------
- task: ArchiveFiles@2
  displayName: 'Package Core Module .xcarchive into a zip file'
  inputs:
    rootFolderOrFile: '$(agent.buildDirectory)/ios-dbp-sdk-core.xcarchive/'
    archiveFile: '$(build.artifactStagingDirectory)/ios-dbp-sdk-core.xcarchive.zip'

# ---------------------------------------
# Publish artifacts
# ---------------------------------------
- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)/ios-dbp-sdk-core.xcarchive.zip'
    artifactName: 'xcarchive-files'
    artifactType: 'container'