# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: CocoaPods@0
  displayName: 'Installing dependencies'
  inputs:
    forceRepoUpdate: true
- task: Xcode@5
  inputs:
    actions: 'clean build analyze archive'
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: 'ios-dbp-sdk.xcworkspace'
    xcodeVersion: '10' # Options: 8, 9, 10, default, specifyPath
    args: '-archivePath $(agent.buildDirectory)/ios-dbp-sdk'

    - task: ArchiveFiles@2
  displayName: 'Package .xcarchive into a zip file'
  inputs:
    rootFolderOrFile: '$(agent.buildDirectory)/ios-dbp-sdk.xcarchive/'
    archiveFile: '$(build.artifactStagingDirectory)/ios-dbp-sdk.xcarchive.zip'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)/ios-dbp-sdk.xcarchive.zip'
    artifactName: 'xcarchive-files'
    artifactType: 'container'
