# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pr:
  - master
  - release-*
  - develop

pool:
  vmImage: 'macos-latest'

variables:
  - group: cs-ios-signing
  - group: git-credentials
  - name: configuration
    value: 'Release'
  - name: sdk
    value: 'iphoneos'

steps:
- checkout: self
  persistCredentials: true

- task: CmdLine@2
  displayName: Adding Alfresco private podspec repository
  inputs:
    script: |
      pod repo add AlfrescoPodspec https://$(gitUser):$(gitPAT)@github.com/Alfresco/alfresco-private-podspecs-ios-sdk.git

# ---------------------------------------
# Run core module tests
# ---------------------------------------
- task: Xcode@5
  displayName: 'Running core module tests'
  inputs:
    actions: 'clean test'
    sdk: 'iphonesimulator'
    xcodeVersion: 11
    scheme: 'AlfrescoCore'
    configuration: 'Debug'
    destinationPlatformOption: 'custom'
    destinationPlatform: 'iOS'
    destinationSimulators: 'iPhone 11'
    xcWorkspacePath: 'AlfrescoCore/AlfrescoCore.xcodeproj'
    useXcpretty: true
    publishJUnitResults: 'build/reports/junit.xml'

- task: CmdLine@2
  displayName: Installing pods for AlfrescoAuth
  inputs:
    script: |
      pod repo update
      cd AlfrescoAuth
      pod install

# ---------------------------------------
# Run auth module tests
# ---------------------------------------
- task: Xcode@5
  displayName: 'Running auth module tests'
  inputs:
    actions: 'clean test'
    sdk: 'iphonesimulator'
    xcodeVersion: 11
    scheme: 'AlfrescoAuth'
    configuration: 'Debug'
    destinationPlatformOption: 'custom'
    destinationPlatform: 'iOS'
    destinationSimulators: 'iPhone 11'
    xcWorkspacePath: 'AlfrescoAuth/AlfrescoAuth.xcworkspace'
    useXcpretty: true
    publishJUnitResults: 'build/reports/junit.xml'

# ---------------------------------------
# Publish test results
# ---------------------------------------
- task: PublishTestResults@2
  displayName: 'Publish test'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'build/reports/junit.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Publishing test results'

# ---------------------------------------
# Build core module
# ---------------------------------------
- task: Xcode@5
  displayName: 'Building Alfresco iOS DBP SDK - core module'
  inputs:
    actions: 'clean build'
    scheme: 'Package iOS'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: 'AlfrescoCore/AlfrescoCore.xcodeproj'
    xcodeVersion: '11'

# ---------------------------------------
# Package core module
# ---------------------------------------
- task: ArchiveFiles@2
  displayName: 'Package core module framework into a zip file'
  inputs:
    rootFolderOrFile: 'AlfrescoCore/AlfrescoCoreInternalRelease/'
    archiveFile: '$(build.artifactStagingDirectory)/ios-dbp-sdk-core-framework.zip'

# ---------------------------------------
# Package auth module
# ---------------------------------------
- task: ArchiveFiles@2
  displayName: 'Package auth module framework into a zip file'
  inputs:
    rootFolderOrFile: 'AlfrescoCore/AlfrescoAuthInternalRelease/'
    archiveFile: '$(build.artifactStagingDirectory)/ios-dbp-sdk-auth-framework.zip'

# ---------------------------------------
# Publish artifacts
# ---------------------------------------
- task: PublishBuildArtifacts@1
  displayName: 'Publish core build artifacts'
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)/ios-dbp-sdk-core-framework.zip'
    artifactName: 'core-framework-files'
    artifactType: 'container'

# ---------------------------------------
# Publish artifacts
# ---------------------------------------
- task: PublishBuildArtifacts@1
  displayName: 'Publish auth build artifacts'
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)/ios-dbp-sdk-auth-framework.zip'
    artifactName: 'auth-framework-files'
    artifactType: 'container'