trigger:
  - master
  - develop

pr: none

pool:
  vmImage: 'macos-latest'

variables:
  - group: git-credentials
  - name: cocoapods_path
    value: $(Pipeline.Workspace)/.cocoapods

steps:
- checkout: self
  persistCredentials: true

- task: CmdLine@2
  displayName: Adding Alfresco private podspec repository
  inputs:
    script: |
      pod repo add AlfrescoPodspec https://$(gitUser):$(gitPAT)@github.com/Alfresco/alfresco-private-podspecs-ios-sdk.git

- task: Cache@2
  inputs:
    key: 'cocoapods | Podfile.lock'
    restoreKeys: cocoapods
    path: $(cocoapods_path)
  displayName: Cache CocoaPods Specs

- task: Cache@2
  inputs:
    key: 'pods | Podfile.lock'
    restoreKeys: pods
    path: Pods
  displayName: Cache Pods

- task: CmdLine@2
  displayName: Installing pods
  inputs:
    script: |
      pod install || pod install --repo-update
  env:
    CP_HOME_DIR: $(cocoapods_path)

- task: CmdLine@2
  displayName: Installing pods for AlfrescoAuth
  inputs:
    script: |
      pod repo update
      cd AlfrescoAuth
      pod install

# ---------------------------------------
# Run auth module tests
# ---------------------------------------
- task: Xcode@5
  displayName: 'Running auth module tests'
  inputs:
    actions: 'clean test'
    sdk: 'iphonesimulator'
    xcodeVersion: 11
    scheme: 'AlfrescoAuth'
    configuration: 'Debug'
    destinationPlatformOption: 'custom'
    destinationPlatform: 'iOS'
    destinationSimulators: 'iPhone 11'
    xcWorkspacePath: 'AlfrescoAuth/AlfrescoAuth.xcworkspace'
    useXcpretty: true
    publishJUnitResults: 'build/reports/junit.xml'

# ---------------------------------------
# Publish test results
# ---------------------------------------
- task: PublishTestResults@2
  displayName: 'Publish test'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'build/reports/junit.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Publishing test results'

# ---------------------------------------
# Build auth module
# ---------------------------------------
- task: Xcode@5
  continueOnError: true
  displayName: 'Building Alfresco Auth iOS Swift API'
  inputs:
    actions: 'clean build'
    scheme: 'Package iOS'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: 'AlfrescoAuth/AlfrescoAuth.xcworkspace'
    xcodeVersion: '11'

# ---------------------------------------
# Package auth module
# ---------------------------------------
- task: ArchiveFiles@2
  displayName: 'Package auth module framework into a zip file'
  inputs:
    rootFolderOrFile: 'AlfrescoAuth/AlfrescoAuthInternalRelease/'
    archiveFile: '$(build.artifactStagingDirectory)/alfresco-ios-swift-auth-api.zip'

# ---------------------------------------
# Publish artifacts
# ---------------------------------------
- task: PublishBuildArtifacts@1
  displayName: 'Publish auth build artifacts'
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)/alfresco-ios-swift-auth-api.zip'
    artifactName: 'auth-framework-files'
    artifactType: 'container'
  