source 'https://github.com/Alfresco/alfresco-private-podspecs-ios-sdk'
source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'

target 'AlfrescoAuth' do
  use_frameworks!

  pod 'AlfrescoCore'
  pod 'AppAuth'

  target 'AlfrescoAuthTests' do
   
  end

end
