source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'

target 'AlfrescoAuth' do
  use_frameworks!

  pod 'AlfrescoCore'
  pod 'AppAuth'
  pod 'SwiftLint'

  target 'AlfrescoAuthTests' do
  end

end
