trigger:
  - master
  - develop

pr: none

pool:
  vmImage: 'macos-latest'

variables:
  - group: git-credentials

steps:
- checkout: self
  persistCredentials: true

# ---------------------------------------
# Run core module tests
# ---------------------------------------
- task: Xcode@5
  displayName: 'Running core module tests'
  inputs:
    actions: 'clean test'
    sdk: 'iphonesimulator'
    xcodeVersion: 11
    scheme: 'AlfrescoCore'
    configuration: 'Debug'
    destinationPlatformOption: 'custom'
    destinationPlatform: 'iOS'
    destinationSimulators: 'iPhone 11'
    xcWorkspacePath: 'AlfrescoCore/AlfrescoCore.xcodeproj'
    useXcpretty: true
    publishJUnitResults: 'build/reports/junit.xml'

# ---------------------------------------
# Publish test results
# ---------------------------------------
- task: PublishTestResults@2
  displayName: 'Publish test'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'build/reports/junit.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Publishing test results'

# ---------------------------------------
# Build core module
# ---------------------------------------
- task: Xcode@5
  displayName: 'Building Alfresco iOS DBP SDK - core module'
  inputs:
    actions: 'clean build'
    scheme: 'Package iOS'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: 'AlfrescoCore/AlfrescoCore.xcodeproj'
    xcodeVersion: '11'

# ---------------------------------------
# Package core module
# ---------------------------------------
- task: ArchiveFiles@2
  displayName: 'Package core module framework into a zip file'
  inputs:
    rootFolderOrFile: 'AlfrescoCore/AlfrescoCoreInternalRelease/'
    archiveFile: '$(build.artifactStagingDirectory)/ios-dbp-sdk-core-framework.zip'

# ---------------------------------------
# Publish artifacts
# ---------------------------------------
- task: PublishBuildArtifacts@1
  displayName: 'Publish core build artifacts'
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)/ios-dbp-sdk-core-framework.zip'
    artifactName: 'core-framework-files'
    artifactType: 'container'
    