source 'https://github.com/Alfresco/alfresco-private-podspecs-ios-sdk.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'
use_frameworks!

target 'SampleApp' do
  pod 'AlfrescoAuth'
  pod 'AlfrescoContent'
  pod 'JWTDecode'
end
#
#post_install do |installer|
#    installer.generated_projects.each do |project|
#          project.targets.each do |target|
#              target.build_configurations.each do |config|
#                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
#               end
#          end
#   end
#end
