source 'https://github.com/Alfresco/alfresco-private-podspecs-ios-sdk.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'
use_frameworks!

target 'SampleApp' do
  pod 'AlfrescoAuth'
  pod 'AlfrescoContent'
  pod 'JWTDecode'
end
