//
// ActionDefinition.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ActionDefinition: Codable {

    /** Identifier of the action definition — used for example when executing an action */
    public var _id: String
    /** name of the action definition, e.g. \&quot;move\&quot; */
    public var name: String?
    /** title of the action definition, e.g. \&quot;Move\&quot; */
    public var title: String?
    /** describes the action definition, e.g. \&quot;This will move the matched item to another space.\&quot; */
    public var _description: String?
    /** QNames of the types this action applies to */
    public var applicableTypes: [String]
    /** whether the basic action definition supports action tracking or not */
    public var trackStatus: Bool
    public var parameterDefinitions: [ActionParameterDefinition]?

    public init(_id: String, name: String?, title: String?, _description: String?, applicableTypes: [String], trackStatus: Bool, parameterDefinitions: [ActionParameterDefinition]?) {
        self._id = _id
        self.name = name
        self.title = title
        self._description = _description
        self.applicableTypes = applicableTypes
        self.trackStatus = trackStatus
        self.parameterDefinitions = parameterDefinitions
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case title
        case _description = "description"
        case applicableTypes
        case trackStatus
        case parameterDefinitions
    }


}

