//
// ActivityPagingList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ActivityPagingList: Codable {

    public var pagination: Pagination
    public var entries: [ActivityEntry]

    public init(pagination: Pagination, entries: [ActivityEntry]) {
        self.pagination = pagination
        self.entries = entries
    }


}

