//
// ActionDefinitionList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ActionDefinitionList: Codable {

    public var list: ActionDefinitionListList?

    public init(list: ActionDefinitionListList?) {
        self.list = list
    }


}

