//
// ActivityPaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ActivityPaging: Codable {

    public var list: ActivityPagingList

    public init(list: ActivityPagingList) {
        self.list = list
    }


}

