//
// AuditEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AuditEntry: Codable {

    public var _id: String
    public var auditApplicationId: String
    public var createdByUser: UserInfo
    public var createdAt: Date
    public var values: JSONValue?

    public init(_id: String, auditApplicationId: String, createdByUser: UserInfo, createdAt: Date, values: JSONValue?) {
        self._id = _id
        self.auditApplicationId = auditApplicationId
        self.createdByUser = createdByUser
        self.createdAt = createdAt
        self.values = values
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case auditApplicationId
        case createdByUser
        case createdAt
        case values
    }


}

