//
// Comment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Comment: Codable {

    public var _id: String
    public var title: String
    public var content: String
    public var createdBy: Person
    public var createdAt: Date
    public var edited: Bool
    public var modifiedBy: Person
    public var modifiedAt: Date
    public var canEdit: Bool
    public var canDelete: Bool

    public init(_id: String, title: String, content: String, createdBy: Person, createdAt: Date, edited: Bool, modifiedBy: Person, modifiedAt: Date, canEdit: Bool, canDelete: Bool) {
        self._id = _id
        self.title = title
        self.content = content
        self.createdBy = createdBy
        self.createdAt = createdAt
        self.edited = edited
        self.modifiedBy = modifiedBy
        self.modifiedAt = modifiedAt
        self.canEdit = canEdit
        self.canDelete = canDelete
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case title
        case content
        case createdBy
        case createdAt
        case edited
        case modifiedBy
        case modifiedAt
        case canEdit
        case canDelete
    }


}

