//
// CommentPaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CommentPaging: Codable {

    public var list: CommentPagingList

    public init(list: CommentPagingList) {
        self.list = list
    }


}

