//
// DeletedNodeBodyRestore.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeletedNodeBodyRestore: Codable {

    public var targetParentId: String?
    public var assocType: String?

    public init(targetParentId: String?, assocType: String?) {
        self.targetParentId = targetParentId
        self.assocType = assocType
    }


}

