//
// DeletedNodesPagingList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeletedNodesPagingList: Codable {

    public var pagination: Pagination?
    public var entries: [DeletedNodeEntry]?

    public init(pagination: Pagination?, entries: [DeletedNodeEntry]?) {
        self.pagination = pagination
        self.entries = entries
    }


}

