//
// DeletedNodeEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeletedNodeEntry: Codable {

    public var entry: DeletedNode?

    public init(entry: DeletedNode?) {
        self.entry = entry
    }


}

