//
// DownloadEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DownloadEntry: Codable {

    public var entry: Download

    public init(entry: Download) {
        self.entry = entry
    }


}

