//
// FavoritePaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FavoritePaging: Codable {

    public var list: FavoritePagingList

    public init(list: FavoritePagingList) {
        self.list = list
    }


}

