//
// FavoriteBodyCreate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FavoriteBodyCreate: Codable {

    public var target: JSONValue

    public init(target: JSONValue) {
        self.target = target
    }


}

