//
// FavoritePagingList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FavoritePagingList: Codable {

    public var pagination: Pagination
    public var entries: [FavoriteEntry]

    public init(pagination: Pagination, entries: [FavoriteEntry]) {
        self.pagination = pagination
        self.entries = entries
    }


}

