//
// GroupBodyCreate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GroupBodyCreate: Codable {

    public var _id: String
    public var displayName: String
    public var parentIds: [String]?

    public init(_id: String, displayName: String, parentIds: [String]?) {
        self._id = _id
        self.displayName = displayName
        self.parentIds = parentIds
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case displayName
        case parentIds
    }


}

