//
// GroupPagingList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GroupPagingList: Codable {

    public var pagination: Pagination?
    public var entries: [GroupEntry]?

    public init(pagination: Pagination?, entries: [GroupEntry]?) {
        self.pagination = pagination
        self.entries = entries
    }


}

