//
// GroupMemberEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GroupMemberEntry: Codable {

    public var entry: GroupMember

    public init(entry: GroupMember) {
        self.entry = entry
    }


}

