//
// Group.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Group: Codable {

    public var _id: String
    public var displayName: String
    public var isRoot: Bool
    public var parentIds: [String]?
    public var zones: [String]?

    public init(_id: String, displayName: String, isRoot: Bool, parentIds: [String]?, zones: [String]?) {
        self._id = _id
        self.displayName = displayName
        self.isRoot = isRoot
        self.parentIds = parentIds
        self.zones = zones
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case displayName
        case isRoot
        case parentIds
        case zones
    }


}

