//
// NodeEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NodeEntry: Codable {

    public var entry: Node

    public init(entry: Node) {
        self.entry = entry
    }


}

