//
// NodeChildAssociationPagingList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NodeChildAssociationPagingList: Codable {

    public var pagination: Pagination?
    public var entries: [NodeChildAssociationEntry]?
    public var source: Node?

    public init(pagination: Pagination?, entries: [NodeChildAssociationEntry]?, source: Node?) {
        self.pagination = pagination
        self.entries = entries
        self.source = source
    }


}

