//
// NodePaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NodePaging: Codable {

    public var list: NodePagingList?

    public init(list: NodePagingList?) {
        self.list = list
    }


}

