//
// NodeBodyCreateAssociation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NodeBodyCreateAssociation: Codable {

    public var assocType: String?

    public init(assocType: String?) {
        self.assocType = assocType
    }


}

