//
// PermissionsBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PermissionsBody: Codable {

    public var isInheritanceEnabled: Bool?
    public var locallySet: [PermissionElement]?

    public init(isInheritanceEnabled: Bool?, locallySet: [PermissionElement]?) {
        self.isInheritanceEnabled = isInheritanceEnabled
        self.locallySet = locallySet
    }


}

