//
// PersonPaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PersonPaging: Codable {

    public var list: PersonPagingList?

    public init(list: PersonPagingList?) {
        self.list = list
    }


}

