//
// PersonNetworkPagingList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PersonNetworkPagingList: Codable {

    public var pagination: Pagination
    public var entries: [PersonNetworkEntry]

    public init(pagination: Pagination, entries: [PersonNetworkEntry]) {
        self.pagination = pagination
        self.entries = entries
    }


}

