//
// PersonNetwork.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A network is the group of users and sites that belong to an organization. Networks are organized by email domain. When a user signs up for an Alfresco account , their email domain becomes their Home Network.  */

public struct PersonNetwork: Codable {

    public enum SubscriptionLevel: String, Codable { 
        case free = "Free"
        case standard = "Standard"
        case enterprise = "Enterprise"
    }
    /** This network&#39;s unique id */
    public var _id: String
    /** Is this the home network? */
    public var homeNetwork: Bool?
    public var isEnabled: Bool
    public var createdAt: Date?
    public var paidNetwork: Bool?
    public var subscriptionLevel: SubscriptionLevel?
    public var quotas: [NetworkQuota]?

    public init(_id: String, homeNetwork: Bool?, isEnabled: Bool, createdAt: Date?, paidNetwork: Bool?, subscriptionLevel: SubscriptionLevel?, quotas: [NetworkQuota]?) {
        self._id = _id
        self.homeNetwork = homeNetwork
        self.isEnabled = isEnabled
        self.createdAt = createdAt
        self.paidNetwork = paidNetwork
        self.subscriptionLevel = subscriptionLevel
        self.quotas = quotas
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case homeNetwork
        case isEnabled
        case createdAt
        case paidNetwork
        case subscriptionLevel
        case quotas
    }


}

