//
// ProbeEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProbeEntry: Codable {

    public var entry: ProbeEntryEntry

    public init(entry: ProbeEntryEntry) {
        self.entry = entry
    }


}

