//
// RatingAggregate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RatingAggregate: Codable {

    public var numberOfRatings: Int
    public var average: Int?

    public init(numberOfRatings: Int, average: Int?) {
        self.numberOfRatings = numberOfRatings
        self.average = average
    }


}

