//
// RatingBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RatingBody: Codable {

    public enum Id: String, Codable { 
        case likes = "likes"
        case fivestar = "fiveStar"
    }
    /** The rating scheme type. Possible values are likes and fiveStar. */
    public var _id: Id
    /** The rating. The type is specific to the rating scheme, boolean for the likes and an integer for the fiveStar */
    public var myRating: String

    public init(_id: Id, myRating: String) {
        self._id = _id
        self.myRating = myRating
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case myRating
    }


}

