//
// RenditionPaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RenditionPaging: Codable {

    public var list: RenditionPagingList?

    public init(list: RenditionPagingList?) {
        self.list = list
    }


}

