//
// RequestSortDefinition.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** How to sort the rows? An array of sort specifications. The array order defines the ordering precedence. */
public typealias RequestSortDefinition = [RequestSortDefinitionInner]
