//
// RequestFacetFields.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Simple facet fields to include The Properties reflect the global properties related to field facts in SOLR. They are descripbed in detail by the SOLR documentation  */

public struct RequestFacetFields: Codable {

    /** Define specifc fields on which to facet (adds SOLR facet.field and f.&lt;field&gt;.facet.* options)  */
    public var facets: [RequestFacetField]?

    public init(facets: [RequestFacetField]?) {
        self.facets = facets
    }


}

