//
// RequestLocalization.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Localization settings */

public struct RequestLocalization: Codable {

    /** A valid timezone id supported by @see java.time.ZoneId */
    public var timezone: String?
    /** A list of Locales definied by IETF BCP 47.  The ordering is significant.  The first locale (leftmost) is used for sort and query localization, whereas the remaining locales are used for query only. */
    public var locales: [String]?

    public init(timezone: String?, locales: [String]?) {
        self.timezone = timezone
        self.locales = locales
    }


}

