//
// RequestTemplatesInner.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RequestTemplatesInner: Codable {

    /** The template name */
    public var name: String?
    /** The template */
    public var template: String?

    public init(name: String?, template: String?) {
        self.name = name
        self.template = template
    }


}

