//
// RequestFilterQueries.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Filter Queries. Constraints that apply to the results set but do not affect the score of each entry. */
public typealias RequestFilterQueries = [RequestFilterQueriesInner]
