//
// RequestFilterQueriesInner.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RequestFilterQueriesInner: Codable {

    /** The filter query expression. For multi-select facets selected facets must be order together  */
    public var query: String?
    /** Tags used exclude the filters from facet evaluation for multi-select facet support */
    public var tags: [String]?

    public init(query: String?, tags: [String]?) {
        self.query = query
        self.tags = tags
    }


}

