//
// RequestFacetIntervals.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Facet Intervals */

public struct RequestFacetIntervals: Codable {

    /** Sets the intervals for all fields. */
    public var sets: [RequestFacetSet]?
    /** Specifies the fields to facet by interval. */
    public var intervals: [RequestFacetIntervalsIntervals]?

    public init(sets: [RequestFacetSet]?, intervals: [RequestFacetIntervalsIntervals]?) {
        self.sets = sets
        self.intervals = intervals
    }


}

