//
// RequestQuery.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Query. */

public struct RequestQuery: Codable {

    public enum Language: String, Codable { 
        case afts = "afts"
        case lucene = "lucene"
        case cmis = "cmis"
    }
    /** The query language in which the query is written. */
    public var language: Language?
    /** The exact search request typed in by the user */
    public var userQuery: String?
    /** The query which may have been generated in some way from the userQuery */
    public var query: String

    public init(language: Language?, userQuery: String?, query: String) {
        self.language = language
        self.userQuery = userQuery
        self.query = query
    }


}

