//
// RequestFacetQueries.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Facet queries to include */
public typealias RequestFacetQueries = [RequestFacetQueriesInner]
