//
// ResultSetContextSpellcheck.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ResultSetContextSpellcheck: Codable {

    public enum ModelType: String, Codable { 
        case searchinsteadfor = "searchInsteadFor"
        case didyoumean = "didYouMean"
    }
    public var type: ModelType?
    /** A suggested alternative query */
    public var suggestion: [String]?

    public init(type: ModelType?, suggestion: [String]?) {
        self.type = type
        self.suggestion = suggestion
    }


}

