//
// ResultBucketsBuckets.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ResultBucketsBuckets: Codable {

    /** The bucket label */
    public var label: String?
    /** The filter query you can use to apply this facet */
    public var filterQuery: String?
    /** The count for the bucket */
    public var count: Int?
    /** An optional field for additional display information */
    public var display: JSONValue?

    public init(label: String?, filterQuery: String?, count: Int?, display: JSONValue?) {
        self.label = label
        self.filterQuery = filterQuery
        self.count = count
        self.display = display
    }


}

