//
// ResultSetContextFacetQueries.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ResultSetContextFacetQueries: Codable {

    public var label: String?
    /** The filter query you can use to apply this facet */
    public var filterQuery: String?
    public var count: Int?

    public init(label: String?, filterQuery: String?, count: Int?) {
        self.label = label
        self.filterQuery = filterQuery
        self.count = count
    }


}

