//
// ResultSetRowEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A row in the result set */

public struct ResultSetRowEntry: Codable {

    public var entry: ResultNode

    public init(entry: ResultNode) {
        self.entry = entry
    }


}

