//
// SearchRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SearchRequest: Codable {

    public var query: RequestQuery
    public var paging: RequestPagination?
    public var include: RequestInclude?
    /** When true, include the original request in the response */
    public var includeRequest: Bool?
    public var fields: RequestFields?
    public var sort: RequestSortDefinition?
    public var templates: RequestTemplates?
    public var defaults: RequestDefaults?
    public var localization: RequestLocalization?
    public var filterQueries: RequestFilterQueries?
    public var facetQueries: RequestFacetQueries?
    public var facetFields: RequestFacetFields?
    public var facetIntervals: RequestFacetIntervals?
    public var pivots: [RequestPivot]?
    public var stats: [RequestStats]?
    public var spellcheck: RequestSpellcheck?
    public var scope: RequestScope?
    public var limits: RequestLimits?
    public var highlight: RequestHighlight?
    public var ranges: [RequestRange]?

    public init(query: RequestQuery, paging: RequestPagination?, include: RequestInclude?, includeRequest: Bool?, fields: RequestFields?, sort: RequestSortDefinition?, templates: RequestTemplates?, defaults: RequestDefaults?, localization: RequestLocalization?, filterQueries: RequestFilterQueries?, facetQueries: RequestFacetQueries?, facetFields: RequestFacetFields?, facetIntervals: RequestFacetIntervals?, pivots: [RequestPivot]?, stats: [RequestStats]?, spellcheck: RequestSpellcheck?, scope: RequestScope?, limits: RequestLimits?, highlight: RequestHighlight?, ranges: [RequestRange]?) {
        self.query = query
        self.paging = paging
        self.include = include
        self.includeRequest = includeRequest
        self.fields = fields
        self.sort = sort
        self.templates = templates
        self.defaults = defaults
        self.localization = localization
        self.filterQueries = filterQueries
        self.facetQueries = facetQueries
        self.facetFields = facetFields
        self.facetIntervals = facetIntervals
        self.pivots = pivots
        self.stats = stats
        self.spellcheck = spellcheck
        self.scope = scope
        self.limits = limits
        self.highlight = highlight
        self.ranges = ranges
    }


}

