//
// SearchEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SearchEntry: Codable {

    /** The score for this row */
    public var score: Float?
    /** Highlight fragments if requested and available. A match can happen in any of the requested field.  */
    public var highlight: [SearchEntryHighlight]?

    public init(score: Float?, highlight: [SearchEntryHighlight]?) {
        self.score = score
        self.highlight = highlight
    }


}

