//
// SharedLinkBodyEmail.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SharedLinkBodyEmail: Codable {

    public var client: String?
    public var message: String?
    public var locale: String?
    public var recipientEmails: [String]?

    public init(client: String?, message: String?, locale: String?, recipientEmails: [String]?) {
        self.client = client
        self.message = message
        self.locale = locale
        self.recipientEmails = recipientEmails
    }


}

