//
// SharedLinkPaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SharedLinkPaging: Codable {

    public var list: SharedLinkPagingList

    public init(list: SharedLinkPagingList) {
        self.list = list
    }


}

