//
// SiteRolePagingList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SiteRolePagingList: Codable {

    public var pagination: Pagination
    public var entries: [SiteRoleEntry]

    public init(pagination: Pagination, entries: [SiteRoleEntry]) {
        self.pagination = pagination
        self.entries = entries
    }


}

