//
// SiteMembershipBodyUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SiteMembershipBodyUpdate: Codable {

    public enum Role: String, Codable { 
        case siteConsumer = "SiteConsumer"
        case siteCollaborator = "SiteCollaborator"
        case siteContributor = "SiteContributor"
        case siteManager = "SiteManager"
    }
    public var role: Role

    public init(role: Role) {
        self.role = role
    }


}

