//
// SiteMembershipRequestBodyCreate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SiteMembershipRequestBodyCreate: Codable {

    public var message: String?
    public var _id: String
    public var title: String?

    public init(message: String?, _id: String, title: String?) {
        self.message = message
        self._id = _id
        self.title = title
    }

    public enum CodingKeys: String, CodingKey { 
        case message
        case _id = "id"
        case title
    }


}

