//
// SiteContainer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SiteContainer: Codable {

    public var _id: String
    public var folderId: String

    public init(_id: String, folderId: String) {
        self._id = _id
        self.folderId = folderId
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case folderId
    }


}

