//
// Ticket.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Ticket: Codable {

    public var _id: String?
    public var userId: String?

    public init(_id: String?, userId: String?) {
        self._id = _id
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case userId
    }


}

