//
// TicketEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TicketEntry: Codable {

    public var entry: Ticket

    public init(entry: Ticket) {
        self.entry = entry
    }


}

