//
// UserInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserInfo: Codable {

    public var displayName: String
    public var _id: String

    public init(displayName: String, _id: String) {
        self.displayName = displayName
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case displayName
        case _id = "id"
    }


}

