//
// VersionEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VersionEntry: Codable {

    public var entry: Version?

    public init(entry: Version?) {
        self.entry = entry
    }


}

