//
// ActionDefinitionListList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ActionDefinitionListList: Codable {

    public var pagination: Pagination?
    public var entries: [ActionDefinition]?

    public init(pagination: Pagination?, entries: [ActionDefinition]?) {
        self.pagination = pagination
        self.entries = entries
    }


}

