//
// ActivityEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ActivityEntry: Codable {

    public var entry: Activity

    public init(entry: Activity) {
        self.entry = entry
    }


}

