//
// AuditEntryEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AuditEntryEntry: Codable {

    public var entry: AuditEntry?

    public init(entry: AuditEntry?) {
        self.entry = entry
    }


}

