//
// ChildAssociationEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChildAssociationEntry: Codable {

    public var entry: ChildAssociation

    public init(entry: ChildAssociation) {
        self.entry = entry
    }


}

