//
// NodeAssociationPaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NodeAssociationPaging: Codable {

    public var list: NodeAssociationPagingList?

    public init(list: NodeAssociationPagingList?) {
        self.list = list
    }


}

