//
// NodeAssociationEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NodeAssociationEntry: Codable {

    public var entry: NodeAssociation

    public init(entry: NodeAssociation) {
        self.entry = entry
    }


}

