//
// NodePagingList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NodePagingList: Codable {

    public var pagination: Pagination?
    public var entries: [NodeEntry]?
    public var source: Node?

    public init(pagination: Pagination?, entries: [NodeEntry]?, source: Node?) {
        self.pagination = pagination
        self.entries = entries
        self.source = source
    }


}

