//
// PathElement.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PathElement: Codable {

    public var _id: String?
    public var name: String?
    public var nodeType: String?
    public var aspectNames: [String]?

    public init(_id: String?, name: String?, nodeType: String?, aspectNames: [String]?) {
        self._id = _id
        self.name = name
        self.nodeType = nodeType
        self.aspectNames = aspectNames
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case nodeType
        case aspectNames
    }


}

