//
// PersonNetworkEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PersonNetworkEntry: Codable {

    public var entry: PersonNetwork

    public init(entry: PersonNetwork) {
        self.entry = entry
    }


}

