//
// PersonNetworkPaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PersonNetworkPaging: Codable {

    public var list: PersonNetworkPagingList

    public init(list: PersonNetworkPagingList) {
        self.list = list
    }


}

