//
// Preference.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A specific preference.  */

public struct Preference: Codable {

    /** The unique id of the preference */
    public var _id: String
    /** The value of the preference. Note that this can be of any JSON type. */
    public var value: String?

    public init(_id: String, value: String?) {
        self._id = _id
        self.value = value
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case value
    }


}

