//
// Rating.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A person can rate an item of content by liking it. They can also remove their like of an item of content. API methods exist to get a list of ratings and to add a new rating.  */

public struct Rating: Codable {

    public var _id: String
    public var aggregate: RatingAggregate
    public var ratedAt: Date?
    /** The rating. The type is specific to the rating scheme, boolean for the likes and an integer for the fiveStar. */
    public var myRating: String?

    public init(_id: String, aggregate: RatingAggregate, ratedAt: Date?, myRating: String?) {
        self._id = _id
        self.aggregate = aggregate
        self.ratedAt = ratedAt
        self.myRating = myRating
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case aggregate
        case ratedAt
        case myRating
    }


}

