//
// RatingPagingList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RatingPagingList: Codable {

    public var pagination: Pagination
    public var entries: [RatingEntry]

    public init(pagination: Pagination, entries: [RatingEntry]) {
        self.pagination = pagination
        self.entries = entries
    }


}

