//
// RequestHighlightFields.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RequestHighlightFields: Codable {

    /** The name of the field to highlight. */
    public var field: String?
    public var snippetCount: Int?
    public var fragmentSize: Int?
    public var mergeContiguous: Bool?
    public var _prefix: String?
    public var _postfix: String?

    public init(field: String?, snippetCount: Int?, fragmentSize: Int?, mergeContiguous: Bool?, _prefix: String?, _postfix: String?) {
        self.field = field
        self.snippetCount = snippetCount
        self.fragmentSize = fragmentSize
        self.mergeContiguous = mergeContiguous
        self._prefix = _prefix
        self._postfix = _postfix
    }

    public enum CodingKeys: String, CodingKey { 
        case field
        case snippetCount
        case fragmentSize
        case mergeContiguous
        case _prefix = "prefix"
        case _postfix = "postfix"
    }


}

