//
// ResultBuckets.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ResultBuckets: Codable {

    /** The field name or its explicit label, if provided on the request */
    public var label: String?
    /** An array of buckets and values */
    public var buckets: [ResultBucketsBuckets]?

    public init(label: String?, buckets: [ResultBucketsBuckets]?) {
        self.label = label
        self.buckets = buckets
    }


}

