//
// RevertBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RevertBody: Codable {

    public var majorVersion: Bool?
    public var comment: String?

    public init(majorVersion: Bool?, comment: String?) {
        self.majorVersion = majorVersion
        self.comment = comment
    }


}

