//
// SiteMembershipRequestEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SiteMembershipRequestEntry: Codable {

    public var entry: SiteMembershipRequest

    public init(entry: SiteMembershipRequest) {
        self.entry = entry
    }


}

