//
// SitePagingList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SitePagingList: Codable {

    public var pagination: Pagination
    public var entries: [SiteEntry]

    public init(pagination: Pagination, entries: [SiteEntry]) {
        self.pagination = pagination
        self.entries = entries
    }


}

