//
// SiteEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SiteEntry: Codable {

    public var entry: Site

    public init(entry: Site) {
        self.entry = entry
    }


}

