//
// SiteContainerPagingList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SiteContainerPagingList: Codable {

    public var pagination: Pagination
    public var entries: [SiteContainerEntry]

    public init(pagination: Pagination, entries: [SiteContainerEntry]) {
        self.pagination = pagination
        self.entries = entries
    }


}

