//
// SiteRoleEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SiteRoleEntry: Codable {

    public var entry: SiteRole

    public init(entry: SiteRole) {
        self.entry = entry
    }


}

