//
// VersionPaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VersionPaging: Codable {

    public var list: VersionPagingList?

    public init(list: VersionPagingList?) {
        self.list = list
    }


}

