//
// AuditAppEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AuditAppEntry: Codable {

    public var entry: AuditApp?

    public init(entry: AuditApp?) {
        self.entry = entry
    }


}

