//
// AuditBodyUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AuditBodyUpdate: Codable {

    public var isEnabled: Bool?

    public init(isEnabled: Bool?) {
        self.isEnabled = isEnabled
    }


}

