//
// AuditAppPagingList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AuditAppPagingList: Codable {

    public var pagination: Pagination?
    public var entries: [AuditAppEntry]?

    public init(pagination: Pagination?, entries: [AuditAppEntry]?) {
        self.pagination = pagination
        self.entries = entries
    }


}

