//
// Capabilities.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Capabilities: Codable {

    public var isAdmin: Bool?
    public var isGuest: Bool?
    public var isMutable: Bool?

    public init(isAdmin: Bool?, isGuest: Bool?, isMutable: Bool?) {
        self.isAdmin = isAdmin
        self.isGuest = isGuest
        self.isMutable = isMutable
    }


}

