//
// Constraint.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Constraint: Codable {

    public var _id: String
    /** the type of the constraint */
    public var type: String?
    /** the human-readable constraint title */
    public var title: String?
    /** the human-readable constraint description */
    public var _description: String?
    public var parameters: [String:JSONValue]?

    public init(_id: String, type: String?, title: String?, _description: String?, parameters: [String:JSONValue]?) {
        self._id = _id
        self.type = type
        self.title = title
        self._description = _description
        self.parameters = parameters
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case type
        case title
        case _description = "description"
        case parameters
    }


}

