//
// DeletedNodesPaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeletedNodesPaging: Codable {

    public var list: DeletedNodesPagingList?

    public init(list: DeletedNodesPagingList?) {
        self.list = list
    }


}

