//
// FavoriteTarget.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FavoriteTarget: Codable {

    public var file: FavoriteTargetNode?
    public var folder: FavoriteTargetNode?
    public var site: Site?

    public init(file: FavoriteTargetNode?, folder: FavoriteTargetNode?, site: Site?) {
        self.file = file
        self.folder = folder
        self.site = site
    }


}

