//
// FavoriteEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FavoriteEntry: Codable {

    public var entry: Favorite

    public init(entry: Favorite) {
        self.entry = entry
    }


}

