//
// Favorite.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A favorite describes an Alfresco entity that a person has marked as a favorite. The target can be a site, file or folder.  */

public struct Favorite: Codable {

    /** The guid of the object that is a favorite. */
    public var targetGuid: String
    /** The time the object was made a favorite. */
    public var createdAt: Date?
    public var target: FavoriteTarget
    /** A subset of the target favorite properties, system properties and properties already available in the target are excluded. */
    public var properties: JSONValue?
    public var allowableOperations: [String]?

    public init(targetGuid: String, createdAt: Date?, target: FavoriteTarget, properties: JSONValue?, allowableOperations: [String]?) {
        self.targetGuid = targetGuid
        self.createdAt = createdAt
        self.target = target
        self.properties = properties
        self.allowableOperations = allowableOperations
    }


}

