//
// FavoriteSiteEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FavoriteSiteEntry: Codable {

    public var entry: FavoriteSite

    public init(entry: FavoriteSite) {
        self.entry = entry
    }


}

