//
// GenericBucket.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A bucket of facet results */

public struct GenericBucket: Codable {

    /** The bucket label */
    public var label: String?
    /** The bucket count */
    public var count: String?
    /** The filter query you can use to apply this facet */
    public var filterQuery: String?
    /** An optional field for additional display information */
    public var display: JSONValue?
    /** An array of buckets and values */
    public var metrics: [GenericMetric]?
    /** Additional list of nested facets */
    public var facets: [JSONValue]?
    public var bucketInfo: GenericBucketBucketInfo?

    public init(label: String?, count: String?, filterQuery: String?, display: JSONValue?, metrics: [GenericMetric]?, facets: [JSONValue]?, bucketInfo: GenericBucketBucketInfo?) {
        self.label = label
        self.filterQuery = filterQuery
        self.display = display
        self.metrics = metrics
        self.facets = facets
        self.bucketInfo = bucketInfo
        self.count = count
    }
}

