//
// GroupMemberPaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GroupMemberPaging: Codable {

    public var list: GroupMemberPagingList?

    public init(list: GroupMemberPagingList?) {
        self.list = list
    }


}

