//
// GroupBodyUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GroupBodyUpdate: Codable {

    public var displayName: String

    public init(displayName: String) {
        self.displayName = displayName
    }


}

