//
// NetworkQuota.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Limits and usage of each quota. A network will have quotas for File space, the number of sites in the network, the number of people in the network, and the number of network administrators  */

public struct NetworkQuota: Codable {

    public var _id: String
    public var limit: Int64
    public var usage: Int64

    public init(_id: String, limit: Int64, usage: Int64) {
        self._id = _id
        self.limit = limit
        self.usage = usage
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case limit
        case usage
    }


}

