//
// NodeChildAssociationEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NodeChildAssociationEntry: Codable {

    public var entry: NodeChildAssociation

    public init(entry: NodeChildAssociation) {
        self.entry = entry
    }


}

