//
// NodeAssociationPagingList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NodeAssociationPagingList: Codable {

    public var pagination: Pagination?
    public var entries: [NodeAssociationEntry]?
    public var source: Node?

    public init(pagination: Pagination?, entries: [NodeAssociationEntry]?, source: Node?) {
        self.pagination = pagination
        self.entries = entries
        self.source = source
    }


}

