//
// Pagination.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Pagination: Codable {

    /** The number of objects in the entries array.  */
    public var count: Int64
    /** A boolean value which is **true** if there are more entities in the collection beyond those in this response. A true value means a request with a larger value for the **skipCount** or the **maxItems** parameter will return more entities.  */
    public var hasMoreItems: Bool
    /** An integer describing the total number of entities in the collection. The API might not be able to determine this value, in which case this property will not be present.  */
    public var totalItems: Int64?
    /** An integer describing how many entities exist in the collection before those included in this list. If there was no **skipCount** parameter then the  default value is 0.  */
    public var skipCount: Int64
    /** The value of the **maxItems** parameter used to generate this list. If there was no **maxItems** parameter then the default value is 100.  */
    public var maxItems: Int64

    public init(count: Int64, hasMoreItems: Bool, totalItems: Int64?, skipCount: Int64, maxItems: Int64) {
        self.count = count
        self.hasMoreItems = hasMoreItems
        self.totalItems = totalItems
        self.skipCount = skipCount
        self.maxItems = maxItems
    }


}

