//
// PathInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PathInfo: Codable {

    public var elements: [PathElement]?
    public var name: String?
    public var isComplete: Bool?

    public init(elements: [PathElement]?, name: String?, isComplete: Bool?) {
        self.elements = elements
        self.name = name
        self.isComplete = isComplete
    }


}

