//
// PermissionsInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PermissionsInfo: Codable {

    public var isInheritanceEnabled: Bool?
    public var inherited: [PermissionElement]?
    public var locallySet: [PermissionElement]?
    public var settable: [String]?

    public init(isInheritanceEnabled: Bool?, inherited: [PermissionElement]?, locallySet: [PermissionElement]?, settable: [String]?) {
        self.isInheritanceEnabled = isInheritanceEnabled
        self.inherited = inherited
        self.locallySet = locallySet
        self.settable = settable
    }


}

