//
// PermissionElement.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PermissionElement: Codable {

    public enum AccessStatus: String, Codable { 
        case allowed = "ALLOWED"
        case denied = "DENIED"
    }
    public var authorityId: String?
    public var name: String?
    public var accessStatus: AccessStatus?

    public init(authorityId: String?, name: String?, accessStatus: AccessStatus?) {
        self.authorityId = authorityId
        self.name = name
        self.accessStatus = accessStatus
    }


}

