//
// Person.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Person: Codable {

    public var _id: String
    public var firstName: String
    public var lastName: String?
    public var displayName: String?
    public var _description: String?
    public var avatarId: String?
    public var email: String
    public var skypeId: String?
    public var googleId: String?
    public var instantMessageId: String?
    public var jobTitle: String?
    public var location: String?
    public var company: Company?
    public var mobile: String?
    public var telephone: String?
    public var statusUpdatedAt: Date?
    public var userStatus: String?
    public var enabled: Bool
    public var emailNotificationsEnabled: Bool?
    public var aspectNames: [String]?
    public var properties: [String:String]?
    public var capabilities: Capabilities?

    public init(_id: String, firstName: String, lastName: String?, displayName: String?, _description: String?, avatarId: String?, email: String, skypeId: String?, googleId: String?, instantMessageId: String?, jobTitle: String?, location: String?, company: Company?, mobile: String?, telephone: String?, statusUpdatedAt: Date?, userStatus: String?, enabled: Bool, emailNotificationsEnabled: Bool?, aspectNames: [String]?, properties: [String:String]?, capabilities: Capabilities?) {
        self._id = _id
        self.firstName = firstName
        self.lastName = lastName
        self.displayName = displayName
        self._description = _description
        self.avatarId = avatarId
        self.email = email
        self.skypeId = skypeId
        self.googleId = googleId
        self.instantMessageId = instantMessageId
        self.jobTitle = jobTitle
        self.location = location
        self.company = company
        self.mobile = mobile
        self.telephone = telephone
        self.statusUpdatedAt = statusUpdatedAt
        self.userStatus = userStatus
        self.enabled = enabled
        self.emailNotificationsEnabled = emailNotificationsEnabled
        self.aspectNames = aspectNames
        self.properties = properties
        self.capabilities = capabilities
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case firstName
        case lastName
        case displayName
        case _description = "description"
        case avatarId
        case email
        case skypeId
        case googleId
        case instantMessageId
        case jobTitle
        case location
        case company
        case mobile
        case telephone
        case statusUpdatedAt
        case userStatus
        case enabled
        case emailNotificationsEnabled
        case aspectNames
        case properties
        case capabilities
    }


}

