//
// Property.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Property: Codable {

    public var _id: String
    /** the human-readable title */
    public var title: String?
    /** the human-readable description */
    public var _description: String?
    /** the default value */
    public var defaultValue: String?
    /** the name of the property type (i.g. d:text) */
    public var dataType: String?
    /** define if the property is multi-valued */
    public var isMultiValued: Bool?
    /** define if the property is mandatory */
    public var isMandatory: Bool?
    /** define if the presence of mandatory properties is enforced */
    public var isMandatoryEnforced: Bool?
    /** define if the property is system maintained */
    public var isProtected: Bool?
    /** list of constraints defined for the property */
    public var constraints: [Constraint]?

    public init(_id: String, title: String?, _description: String?, defaultValue: String?, dataType: String?, isMultiValued: Bool?, isMandatory: Bool?, isMandatoryEnforced: Bool?, isProtected: Bool?, constraints: [Constraint]?) {
        self._id = _id
        self.title = title
        self._description = _description
        self.defaultValue = defaultValue
        self.dataType = dataType
        self.isMultiValued = isMultiValued
        self.isMandatory = isMandatory
        self.isMandatoryEnforced = isMandatoryEnforced
        self.isProtected = isProtected
        self.constraints = constraints
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case title
        case _description = "description"
        case defaultValue
        case dataType
        case isMultiValued
        case isMandatory
        case isMandatoryEnforced
        case isProtected
        case constraints
    }


}

