//
// RatingPaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RatingPaging: Codable {

    public var list: RatingPagingList

    public init(list: RatingPagingList) {
        self.list = list
    }


}

