//
// Rendition.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Rendition: Codable {

    public enum Status: String, Codable { 
        case created = "CREATED"
        case notCreated = "NOT_CREATED"
    }
    public var _id: String?
    public var content: ContentInfo?
    public var status: Status?

    public init(_id: String?, content: ContentInfo?, status: Status?) {
        self._id = _id
        self.content = content
        self.status = status
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case content
        case status
    }


}

