//
// RequestFacetIntervalsIntervals.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RequestFacetIntervalsIntervals: Codable {

    /** The field to facet on */
    public var field: String?
    /** A label to use to identify the field facet */
    public var label: String?
    /** Sets the intervals for all fields. */
    public var sets: [RequestFacetSet]?

    public init(field: String?, label: String?, sets: [RequestFacetSet]?) {
        self.field = field
        self.label = label
        self.sets = sets
    }


}

