//
// RequestRange.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Facet range */

public struct RequestRange: Codable {

    /** The name of the field to perform range */
    public var field: String?
    /** The start of the range */
    public var start: String?
    /** The end of the range */
    public var end: String?
    /** Bucket size */
    public var gap: String?
    /** If true means that the last bucket will end at “end” even if it is less than “gap” wide. */
    public var hardend: Bool?
    /** before, after, between, non, all */
    public var other: [String]?
    /** lower, upper, edge, outer, all */
    public var include: [String]?
    /** A label to include as a pivot reference */
    public var label: String?
    /** Filter queries to exclude when calculating statistics */
    public var excludeFilters: [String]?

    public init(field: String?, start: String?, end: String?, gap: String?, hardend: Bool?, other: [String]?, include: [String]?, label: String?, excludeFilters: [String]?) {
        self.field = field
        self.start = start
        self.end = end
        self.gap = gap
        self.hardend = hardend
        self.other = other
        self.include = include
        self.label = label
        self.excludeFilters = excludeFilters
    }


}

