//
// RequestStats.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A list of stats request. */

public struct RequestStats: Codable {

    /** The stats field */
    public var field: String?
    /** A label to include for reference the stats field */
    public var label: String?
    /** The minimum value of the field */
    public var min: Bool?
    /** The maximum value of the field */
    public var max: Bool?
    /** The sum of all values of the field */
    public var sum: Bool?
    /** The number which have a value for this field */
    public var countValues: Bool?
    /** The number which do not have a value for this field */
    public var missing: Bool?
    /** The average */
    public var mean: Bool?
    /** Standard deviation */
    public var stddev: Bool?
    /** Sum of all values squared */
    public var sumOfSquares: Bool?
    /** The set of all distinct values for the field (This can be very expensive to calculate) */
    public var distinctValues: Bool?
    /** The number of distinct values  (This can be very expensive to calculate) */
    public var countDistinct: Bool?
    /** A statistical approximation of the number of distinct values */
    public var cardinality: Bool?
    /** Number between 0.0 and 1.0 indicating how aggressively the algorithm should try to be accurate. Used with boolean cardinality flag. */
    public var cardinalityAccuracy: Float?
    /** A list of filters to exclude */
    public var excludeFilters: [String]?
    /** A list of percentile values, e.g. \&quot;1,99,99.9\&quot; */
    public var percentiles: [Float]?

    public init(field: String?, label: String?, min: Bool?, max: Bool?, sum: Bool?, countValues: Bool?, missing: Bool?, mean: Bool?, stddev: Bool?, sumOfSquares: Bool?, distinctValues: Bool?, countDistinct: Bool?, cardinality: Bool?, cardinalityAccuracy: Float?, excludeFilters: [String]?, percentiles: [Float]?) {
        self.field = field
        self.label = label
        self.min = min
        self.max = max
        self.sum = sum
        self.countValues = countValues
        self.missing = missing
        self.mean = mean
        self.stddev = stddev
        self.sumOfSquares = sumOfSquares
        self.distinctValues = distinctValues
        self.countDistinct = countDistinct
        self.cardinality = cardinality
        self.cardinalityAccuracy = cardinalityAccuracy
        self.excludeFilters = excludeFilters
        self.percentiles = percentiles
    }


}

