//
// RequestScope.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Scope */

public struct RequestScope: Codable {

    public enum Locations: String, Codable { 
        case nodes = "nodes"
        case versions = "versions"
        case deletedNodes = "deleted-nodes"
    }
    /** The locations to include in the query  */
    public var locations: Locations?

    public init(locations: Locations?) {
        self.locations = locations
    }


}

