//
// RequestLimits.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Limit the time and resources used for query execution */

public struct RequestLimits: Codable {

    /** Maximum time for post query permission evaluation */
    public var permissionEvaluationTime: Int?
    /** Maximum count of post query permission evaluations */
    public var permissionEvaluationCount: Int?

    public init(permissionEvaluationTime: Int?, permissionEvaluationCount: Int?) {
        self.permissionEvaluationTime = permissionEvaluationTime
        self.permissionEvaluationCount = permissionEvaluationCount
    }


}

