//
// RequestFacetQueriesInner.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RequestFacetQueriesInner: Codable {

    /** A facet query */
    public var query: String?
    /** A label to include in place of the facet query */
    public var label: String?

    public init(query: String?, label: String?) {
        self.query = query
        self.label = label
    }


}

