//
// RequestFacetSet.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The interval to Set */

public struct RequestFacetSet: Codable {

    /** A label to use to identify the set */
    public var label: String?
    /** The start of the range */
    public var start: String?
    /** The end of the range */
    public var end: String?
    /** When true, the set will include values greater or equal to \&quot;start\&quot; */
    public var startInclusive: Bool?
    /** When true, the set will include values less than or equal to \&quot;end\&quot; */
    public var endInclusive: Bool?

    public init(label: String?, start: String?, end: String?, startInclusive: Bool?, endInclusive: Bool?) {
        self.label = label
        self.start = start
        self.end = end
        self.startInclusive = startInclusive
        self.endInclusive = endInclusive
    }


}

