//
// RequestSortDefinitionInner.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RequestSortDefinitionInner: Codable {

    public enum ModelType: String, Codable { 
        case field = "FIELD"
        case document = "DOCUMENT"
        case score = "SCORE"
    }
    /** How to order - using a field, when position of the document in the index, score/relevence. */
    public var type: ModelType?
    /** The name of the field */
    public var field: String?
    /** The sort order. (The ordering of nulls is determined by the SOLR configuration) */
    public var ascending: Bool?

    public init(type: ModelType?, field: String?, ascending: Bool?) {
        self.type = type
        self.field = field
        self.ascending = ascending
    }


}

