//
// ResultSetPaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Query results */

public struct ResultSetPaging: Codable {

    public var list: ResultSetPagingList?

    public init(list: ResultSetPagingList?) {
        self.list = list
    }


}

