//
// ResultSetContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Context that applies to the whole result set */

public struct ResultSetContext: Codable {

    public var consistency: ResponseConsistency?
    public var request: SearchRequest?
    /** The counts from facet queries */
    public var facetQueries: [ResultSetContextFacetQueries]?
    /** The counts from field facets */
    public var facetsFields: [ResultBuckets]?
    /** The faceted response */
    public var facets: [GenericFacetResponse]?
    /** Suggested corrections  If zero results were found for the original query then a single entry of type \&quot;searchInsteadFor\&quot; will be returned. If alternatives were found that return more results than the original query they are returned as \&quot;didYouMean\&quot; options. The highest quality suggestion is first.  */
    public var spellcheck: [ResultSetContextSpellcheck]?

    public init(consistency: ResponseConsistency?, request: SearchRequest?, facetQueries: [ResultSetContextFacetQueries]?, facetsFields: [ResultBuckets]?, facets: [GenericFacetResponse]?, spellcheck: [ResultSetContextSpellcheck]?) {
        self.consistency = consistency
        self.request = request
        self.facetQueries = facetQueries
        self.facetsFields = facetsFields
        self.facets = facets
        self.spellcheck = spellcheck
    }


}

