//
// SearchEntryHighlight.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SearchEntryHighlight: Codable {

    /** The field where a match occured (one of the fields defined on the request) */
    public var field: String?
    /** Any number of snippets for the specified field highlighting the matching text */
    public var snippets: [String]?

    public init(field: String?, snippets: [String]?) {
        self.field = field
        self.snippets = snippets
    }


}

