//
// SiteContainerPaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SiteContainerPaging: Codable {

    public var list: SiteContainerPagingList

    public init(list: SiteContainerPagingList) {
        self.list = list
    }


}

