//
// SiteBodyCreate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SiteBodyCreate: Codable {

    public enum Visibility: String, Codable { 
        case _public = "PUBLIC"
        case _private = "PRIVATE"
        case moderated = "MODERATED"
    }
    public var _id: String?
    public var title: String
    public var _description: String?
    public var visibility: Visibility

    public init(_id: String?, title: String, _description: String?, visibility: Visibility) {
        self._id = _id
        self.title = title
        self._description = _description
        self.visibility = visibility
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case title
        case _description = "description"
        case visibility
    }


}

