//
// SiteMembershipRequestBodyUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SiteMembershipRequestBodyUpdate: Codable {

    public var message: String?

    public init(message: String?) {
        self.message = message
    }


}

