//
// SiteMemberPaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SiteMemberPaging: Codable {

    public var list: SiteMemberPagingList

    public init(list: SiteMemberPagingList) {
        self.list = list
    }


}

