//
// SiteGroupEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SiteGroupEntry: Codable {

    public var entry: SiteGroup

    public init(entry: SiteGroup) {
        self.entry = entry
    }


}

