//
// SiteGroup.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SiteGroup: Codable {

    public enum Role: String, Codable { 
        case siteConsumer = "SiteConsumer"
        case siteCollaborator = "SiteCollaborator"
        case siteContributor = "SiteContributor"
        case siteManager = "SiteManager"
    }
    public var _id: String
    public var group: GroupMember
    public var role: Role

    public init(_id: String, group: GroupMember, role: Role) {
        self._id = _id
        self.group = group
        self.role = role
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case group
        case role
    }


}

