//
// SiteMember.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SiteMember: Codable {

    public enum Role: String, Codable { 
        case siteConsumer = "SiteConsumer"
        case siteCollaborator = "SiteCollaborator"
        case siteContributor = "SiteContributor"
        case siteManager = "SiteManager"
    }
    public var _id: String
    public var person: Person
    public var role: Role
    public var isMemberOfGroup: Bool?

    public init(_id: String, person: Person, role: Role, isMemberOfGroup: Bool?) {
        self._id = _id
        self.person = person
        self.role = role
        self.isMemberOfGroup = isMemberOfGroup
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case person
        case role
        case isMemberOfGroup
    }


}

