//
// SiteGroupPaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SiteGroupPaging: Codable {

    public var list: SiteGroupPagingList

    public init(list: SiteGroupPagingList) {
        self.list = list
    }


}

