//
// SiteMembershipRequestPagingList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SiteMembershipRequestPagingList: Codable {

    public var pagination: Pagination
    public var entries: [SiteMembershipRequestEntry]

    public init(pagination: Pagination, entries: [SiteMembershipRequestEntry]) {
        self.pagination = pagination
        self.entries = entries
    }


}

