//
// SiteMembershipRequestWithPersonPagingList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SiteMembershipRequestWithPersonPagingList: Codable {

    public var pagination: Pagination
    public var entries: [SiteMembershipRequestWithPersonEntry]

    public init(pagination: Pagination, entries: [SiteMembershipRequestWithPersonEntry]) {
        self.pagination = pagination
        self.entries = entries
    }


}

