//
// SiteMembershipRequestWithPersonPaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SiteMembershipRequestWithPersonPaging: Codable {

    public var list: SiteMembershipRequestWithPersonPagingList

    public init(list: SiteMembershipRequestWithPersonPagingList) {
        self.list = list
    }


}

