//
// SitePaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SitePaging: Codable {

    public var list: SitePagingList

    public init(list: SitePagingList) {
        self.list = list
    }


}

