//
// SiteMembershipRequestPaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SiteMembershipRequestPaging: Codable {

    public var list: SiteMembershipRequestPagingList

    public init(list: SiteMembershipRequestPagingList) {
        self.list = list
    }


}

