//
// SiteMembershipApprovalBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SiteMembershipApprovalBody: Codable {

    public var role: String?

    public init(role: String?) {
        self.role = role
    }


}

