//
// TagEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TagEntry: Codable {

    public var entry: Tag

    public init(entry: Tag) {
        self.entry = entry
    }


}

