//
// TagPaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TagPaging: Codable {

    public var list: TagPagingList

    public init(list: TagPagingList) {
        self.list = list
    }


}

