//
// TicketBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TicketBody: Codable {

    public var userId: String?
    public var password: String?

    public init(userId: String?, password: String?) {
        self.userId = userId
        self.password = password
    }


}

