trigger:
  - master
  - develop

pr: none

pool:
  vmImage: 'macos-latest'

variables:
  - group: git-credentials

steps:
- checkout: self
  persistCredentials: true

- task: CmdLine@2
  displayName: Check integrity of swagger library
  inputs:
    script: |
      cd AlfrescoContent
      pod repo add alfresco-ios-swift-api https://$(gitUser):$(gitPAT)@github.com/Alfresco/alfresco-ios-swift-api.git
      pod spec lint --sources='https://github.com/Alfresco/alfresco-ios-swift-api.git,https://github.com/CocoaPods/Specs.git' --allow-warnings