//
// VersionsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class VersionsAPI {
    /**
     Delete a version
     
     - parameter nodeId: (path) The identifier of a node. 
     - parameter versionId: (path) The identifier of a version, ie. version label, within the version history of a node. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteVersion(nodeId: String, versionId: String, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        deleteVersionWithRequestBuilder(nodeId: nodeId, versionId: versionId).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Delete a version
     - DELETE /alfresco/versions/1/nodes/{nodeId}/versions/{versionId}
     - **Note:** this endpoint is available in Alfresco 5.2 and newer versions.  Delete the version identified by **versionId** and **nodeId*.  If the version is successfully deleted then the content and metadata for that versioned node will be deleted and will no longer appear in the version history. This operation cannot be undone.  If the most recent version is deleted the live node will revert to the next most recent version.  We currently do not allow the last version to be deleted. If you wish to clear the history then you can remove the \"cm:versionable\" aspect (via update node) which will also disable versioning. In this case, you can re-enable versioning by adding back the \"cm:versionable\" aspect or using the version  params (majorVersion and comment) on a subsequent file content update. 
     - BASIC:
       - type: basic
       - name: basicAuth
     
     - parameter nodeId: (path) The identifier of a node. 
     - parameter versionId: (path) The identifier of a version, ie. version label, within the version history of a node. 

     - returns: RequestBuilder<Void> 
     */
    open class func deleteVersionWithRequestBuilder(nodeId: String, versionId: String) -> RequestBuilder<Void> {
        var path = "/alfresco/versions/1/nodes/{nodeId}/versions/{versionId}"
        let nodeIdPreEscape = "\(nodeId)"
        let nodeIdPostEscape = nodeIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{nodeId}", with: nodeIdPostEscape, options: .literal, range: nil)
        let versionIdPreEscape = "\(versionId)"
        let versionIdPostEscape = versionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{versionId}", with: versionIdPostEscape, options: .literal, range: nil)
        let URLString = AlfrescoContentServicesAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = AlfrescoContentServicesAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get version information
     
     - parameter nodeId: (path) The identifier of a node. 
     - parameter versionId: (path) The identifier of a version, ie. version label, within the version history of a node. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getVersion(nodeId: String, versionId: String, completion: @escaping ((_ data: VersionEntry?,_ error: Error?) -> Void)) {
        getVersionWithRequestBuilder(nodeId: nodeId, versionId: versionId).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get version information
     - GET /alfresco/versions/1/nodes/{nodeId}/versions/{versionId}
     - **Note:** this endpoint is available in Alfresco 5.2 and newer versions.  Gets the version information for **versionId** of file node **nodeId**. 
     - BASIC:
       - type: basic
       - name: basicAuth
     - examples: [{contentType=application/json, example={
  "entry" : {
    "aspectNames" : [ "aspectNames", "aspectNames" ],
    "isFolder" : true,
    "isFile" : true,
    "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
    "modifiedByUser" : {
      "displayName" : "displayName",
      "id" : "id"
    },
    "versionComment" : "versionComment",
    "name" : "name",
    "id" : "id",
    "nodeType" : "nodeType",
    "content" : {
      "sizeInBytes" : 0,
      "mimeTypeName" : "mimeTypeName",
      "mimeTypeGroup" : "mimeTypeGroup",
      "mimeType" : "mimeType",
      "encoding" : "encoding"
    },
    "properties" : "{}"
  }
}}]
     
     - parameter nodeId: (path) The identifier of a node. 
     - parameter versionId: (path) The identifier of a version, ie. version label, within the version history of a node. 

     - returns: RequestBuilder<VersionEntry> 
     */
    open class func getVersionWithRequestBuilder(nodeId: String, versionId: String) -> RequestBuilder<VersionEntry> {
        var path = "/alfresco/versions/1/nodes/{nodeId}/versions/{versionId}"
        let nodeIdPreEscape = "\(nodeId)"
        let nodeIdPostEscape = nodeIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{nodeId}", with: nodeIdPostEscape, options: .literal, range: nil)
        let versionIdPreEscape = "\(versionId)"
        let versionIdPostEscape = versionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{versionId}", with: versionIdPostEscape, options: .literal, range: nil)
        let URLString = AlfrescoContentServicesAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<VersionEntry>.Type = AlfrescoContentServicesAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get version content
     
     - parameter nodeId: (path) The identifier of a node. 
     - parameter versionId: (path) The identifier of a version, ie. version label, within the version history of a node. 
     - parameter attachment: (query) **true** enables a web browser to download the file as an attachment. **false** means a web browser may preview the file in a new tab or window, but not download the file.  You can only set this parameter to **false** if the content type of the file is in the supported list; for example, certain image files and PDF files.  If the content type is not supported for preview, then a value of **false**  is ignored, and the attachment will be returned in the response.  (optional, default to true)
     - parameter ifModifiedSince: (header) Only returns the content if it has been modified since the date provided. Use the date format defined by HTTP. For example, &#x60;Wed, 09 Mar 2016 16:56:34 GMT&#x60;.  (optional)
     - parameter range: (header) The Range header indicates the part of a document that the server should return. Single part request supported, for example: bytes&#x3D;1-10.  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getVersionContent(nodeId: String, versionId: String, attachment: Bool? = nil, ifModifiedSince: Date? = nil, range: String? = nil, completion: @escaping ((_ data: URL?,_ error: Error?) -> Void)) {
        getVersionContentWithRequestBuilder(nodeId: nodeId, versionId: versionId, attachment: attachment, ifModifiedSince: ifModifiedSince, range: range).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get version content
     - GET /alfresco/versions/1/nodes/{nodeId}/versions/{versionId}/content
     - **Note:** this endpoint is available in Alfresco 5.2 and newer versions.  Gets the version content for **versionId** of file node **nodeId**. 
     - BASIC:
       - type: basic
       - name: basicAuth
     - examples: [{output=none}]
     
     - parameter nodeId: (path) The identifier of a node. 
     - parameter versionId: (path) The identifier of a version, ie. version label, within the version history of a node. 
     - parameter attachment: (query) **true** enables a web browser to download the file as an attachment. **false** means a web browser may preview the file in a new tab or window, but not download the file.  You can only set this parameter to **false** if the content type of the file is in the supported list; for example, certain image files and PDF files.  If the content type is not supported for preview, then a value of **false**  is ignored, and the attachment will be returned in the response.  (optional, default to true)
     - parameter ifModifiedSince: (header) Only returns the content if it has been modified since the date provided. Use the date format defined by HTTP. For example, &#x60;Wed, 09 Mar 2016 16:56:34 GMT&#x60;.  (optional)
     - parameter range: (header) The Range header indicates the part of a document that the server should return. Single part request supported, for example: bytes&#x3D;1-10.  (optional)

     - returns: RequestBuilder<URL> 
     */
    open class func getVersionContentWithRequestBuilder(nodeId: String, versionId: String, attachment: Bool? = nil, ifModifiedSince: Date? = nil, range: String? = nil) -> RequestBuilder<URL> {
        var path = "/alfresco/versions/1/nodes/{nodeId}/versions/{versionId}/content"
        let nodeIdPreEscape = "\(nodeId)"
        let nodeIdPostEscape = nodeIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{nodeId}", with: nodeIdPostEscape, options: .literal, range: nil)
        let versionIdPreEscape = "\(versionId)"
        let versionIdPostEscape = versionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{versionId}", with: versionIdPostEscape, options: .literal, range: nil)
        let URLString = AlfrescoContentServicesAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "attachment": attachment
        ])
        let nillableHeaders: [String: Any?] = [
            "If-Modified-Since": ifModifiedSince?.encodeToJSON(),
            "Range": range
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<URL>.Type = AlfrescoContentServicesAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**
     List version history
     
     - parameter nodeId: (path) The identifier of a node. 
     - parameter include: (query) Returns additional information about the version node. The following optional fields can be requested: * properties * aspectNames  (optional)
     - parameter fields: (query) A list of field names.  You can use this parameter to restrict the fields returned within a response if, for example, you want to save on overall bandwidth.  The list applies to a returned individual entity or entries within a collection.  If the API method also supports the **include** parameter, then the fields specified in the **include** parameter are returned in addition to those specified in the **fields** parameter.  (optional)
     - parameter skipCount: (query) The number of entities that exist in the collection before those included in this list.  If not supplied then the default value is 0.  (optional, default to 0)
     - parameter maxItems: (query) The maximum number of items to return in the list.  If not supplied then the default value is 100.  (optional, default to 100)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func listVersionHistory(nodeId: String, include: [String]? = nil, fields: [String]? = nil, skipCount: Int? = nil, maxItems: Int? = nil, completion: @escaping ((_ data: VersionPaging?,_ error: Error?) -> Void)) {
        listVersionHistoryWithRequestBuilder(nodeId: nodeId, include: include, fields: fields, skipCount: skipCount, maxItems: maxItems).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     List version history
     - GET /alfresco/versions/1/nodes/{nodeId}/versions
     - **Note:** this endpoint is available in Alfresco 5.2 and newer versions.  Gets the version history as an ordered list of versions for the specified **nodeId**.  The list is ordered in descending modified order. So the most recent version is first and  the original version is last in the list.  
     - BASIC:
       - type: basic
       - name: basicAuth
     - examples: [{contentType=application/json, example={
  "list" : {
    "entries" : [ {
      "entry" : {
        "aspectNames" : [ "aspectNames", "aspectNames" ],
        "isFolder" : true,
        "isFile" : true,
        "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
        "modifiedByUser" : {
          "displayName" : "displayName",
          "id" : "id"
        },
        "versionComment" : "versionComment",
        "name" : "name",
        "id" : "id",
        "nodeType" : "nodeType",
        "content" : {
          "sizeInBytes" : 0,
          "mimeTypeName" : "mimeTypeName",
          "mimeTypeGroup" : "mimeTypeGroup",
          "mimeType" : "mimeType",
          "encoding" : "encoding"
        },
        "properties" : "{}"
      }
    }, {
      "entry" : {
        "aspectNames" : [ "aspectNames", "aspectNames" ],
        "isFolder" : true,
        "isFile" : true,
        "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
        "modifiedByUser" : {
          "displayName" : "displayName",
          "id" : "id"
        },
        "versionComment" : "versionComment",
        "name" : "name",
        "id" : "id",
        "nodeType" : "nodeType",
        "content" : {
          "sizeInBytes" : 0,
          "mimeTypeName" : "mimeTypeName",
          "mimeTypeGroup" : "mimeTypeGroup",
          "mimeType" : "mimeType",
          "encoding" : "encoding"
        },
        "properties" : "{}"
      }
    } ],
    "pagination" : {
      "maxItems" : 5,
      "hasMoreItems" : true,
      "totalItems" : 6,
      "count" : 0,
      "skipCount" : 1
    }
  }
}}]
     
     - parameter nodeId: (path) The identifier of a node. 
     - parameter include: (query) Returns additional information about the version node. The following optional fields can be requested: * properties * aspectNames  (optional)
     - parameter fields: (query) A list of field names.  You can use this parameter to restrict the fields returned within a response if, for example, you want to save on overall bandwidth.  The list applies to a returned individual entity or entries within a collection.  If the API method also supports the **include** parameter, then the fields specified in the **include** parameter are returned in addition to those specified in the **fields** parameter.  (optional)
     - parameter skipCount: (query) The number of entities that exist in the collection before those included in this list.  If not supplied then the default value is 0.  (optional, default to 0)
     - parameter maxItems: (query) The maximum number of items to return in the list.  If not supplied then the default value is 100.  (optional, default to 100)

     - returns: RequestBuilder<VersionPaging> 
     */
    open class func listVersionHistoryWithRequestBuilder(nodeId: String, include: [String]? = nil, fields: [String]? = nil, skipCount: Int? = nil, maxItems: Int? = nil) -> RequestBuilder<VersionPaging> {
        var path = "/alfresco/versions/1/nodes/{nodeId}/versions"
        let nodeIdPreEscape = "\(nodeId)"
        let nodeIdPostEscape = nodeIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{nodeId}", with: nodeIdPostEscape, options: .literal, range: nil)
        let URLString = AlfrescoContentServicesAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "include": include, 
            "fields": fields, 
            "skipCount": skipCount?.encodeToJSON(), 
            "maxItems": maxItems?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<VersionPaging>.Type = AlfrescoContentServicesAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Revert a version
     
     - parameter nodeId: (path) The identifier of a node. 
     - parameter versionId: (path) The identifier of a version, ie. version label, within the version history of a node. 
     - parameter revertBody: (body) Optionally, specify a version comment and whether this should be a major version, or not. 
     - parameter fields: (query) A list of field names.  You can use this parameter to restrict the fields returned within a response if, for example, you want to save on overall bandwidth.  The list applies to a returned individual entity or entries within a collection.  If the API method also supports the **include** parameter, then the fields specified in the **include** parameter are returned in addition to those specified in the **fields** parameter.  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func revertVersion(nodeId: String, versionId: String, revertBody: RevertBody, fields: [String]? = nil, completion: @escaping ((_ data: VersionEntry?,_ error: Error?) -> Void)) {
        revertVersionWithRequestBuilder(nodeId: nodeId, versionId: versionId, revertBody: revertBody, fields: fields).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Revert a version
     - POST /alfresco/versions/1/nodes/{nodeId}/versions/{versionId}/revert
     - **Note:** this endpoint is available in Alfresco 5.2 and newer versions.  Attempts to revert the version identified by **versionId** and **nodeId** to the live node.  If the node is successfully reverted then the content and metadata for that versioned node will be promoted to the live node and a new version will appear in the version history. 
     - BASIC:
       - type: basic
       - name: basicAuth
     - examples: [{contentType=application/json, example={
  "entry" : {
    "aspectNames" : [ "aspectNames", "aspectNames" ],
    "isFolder" : true,
    "isFile" : true,
    "modifiedAt" : "2000-01-23T04:56:07.000+00:00",
    "modifiedByUser" : {
      "displayName" : "displayName",
      "id" : "id"
    },
    "versionComment" : "versionComment",
    "name" : "name",
    "id" : "id",
    "nodeType" : "nodeType",
    "content" : {
      "sizeInBytes" : 0,
      "mimeTypeName" : "mimeTypeName",
      "mimeTypeGroup" : "mimeTypeGroup",
      "mimeType" : "mimeType",
      "encoding" : "encoding"
    },
    "properties" : "{}"
  }
}}]
     
     - parameter nodeId: (path) The identifier of a node. 
     - parameter versionId: (path) The identifier of a version, ie. version label, within the version history of a node. 
     - parameter revertBody: (body) Optionally, specify a version comment and whether this should be a major version, or not. 
     - parameter fields: (query) A list of field names.  You can use this parameter to restrict the fields returned within a response if, for example, you want to save on overall bandwidth.  The list applies to a returned individual entity or entries within a collection.  If the API method also supports the **include** parameter, then the fields specified in the **include** parameter are returned in addition to those specified in the **fields** parameter.  (optional)

     - returns: RequestBuilder<VersionEntry> 
     */
    open class func revertVersionWithRequestBuilder(nodeId: String, versionId: String, revertBody: RevertBody, fields: [String]? = nil) -> RequestBuilder<VersionEntry> {
        var path = "/alfresco/versions/1/nodes/{nodeId}/versions/{versionId}/revert"
        let nodeIdPreEscape = "\(nodeId)"
        let nodeIdPostEscape = nodeIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{nodeId}", with: nodeIdPostEscape, options: .literal, range: nil)
        let versionIdPreEscape = "\(versionId)"
        let versionIdPostEscape = versionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{versionId}", with: versionIdPostEscape, options: .literal, range: nil)
        let URLString = AlfrescoContentServicesAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: revertBody)

        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "fields": fields
        ])

        let requestBuilder: RequestBuilder<VersionEntry>.Type = AlfrescoContentServicesAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
